name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump even if no changes"
        required: false
        type: choice
        default: "false"
        options:
          - "true"
          - "false"

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@448722165938617ea8b814719c33d73122390c9a # v1.2.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0

      - name: Bump
        uses: spotdemo4/bumper@8b9df22ba64a8cbc777429d5e96fedc6e6346c6c # v0.2.3
        with:
          force: ${{ inputs.force }}
          files: |-
            .github/README.md
