name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@66d8f152d46a575eda9336e09d6f7fccc7756b16 # v1.1.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0

      - name: Bump
        uses: spotdemo4/bumper@f04a147ddd35d7eb198b7784ad1c2c277c18d23e # v0.1.22
        with:
          files: |-
            .github/README.md
